### ISSUE TITLE
file formats for oases

### ISSUE THREAD

**Issue by webbchen** [SchulzLab/KREATION#2]
Dear authors

When passing 2 paired-end read files in fastq format to the oases config file the pipeline failed:
"
velveth: /data/anne_webb/Trimmed_Vfaba/Hedin_transcriptome/Hedin_forward_reads_all.fastq does not seem to be in FastA format
"
When passing the reads like so:
"
#Rest of the command
-d "-fastq -shortPaired /forward_reads_all.fastq reverse_reads_all.fastq" -p "-ins_length 390"
"
the problem went away. Passing -fastq and -shortPaired in under -p "" didn't work.

I suggest pointing this out in the description as reads in fastq format are commonly used for assemblies.

Kind regards,

Anne

**Comment by ddurai** [comment]
Dear Anne
Thank you for notifying us about the problem. We have updated the description so that the usage is bit more easier. Please mail us if you have any other questions/suggestions about KREATION. 

Thank you for using KREATION

regards
Dilip

**Comment by SchulzLab** [comment]
Dear Anne,
thanks for the comment. This behavior is inherited from the way Oases works, building on Velvet. I added a notification that the users should still consult the manual of the individual assemblers for detailed parametrization of assemblers through the KREATION script. If there are some general problems that we did not face, we are happy to address them.

Kind regards,
Marcel
